export const LOGIN_PAGE = 'login'
export const SIGN_UP_PAGE = 'sign-up'
export const BASE_PAGE = 'base'
export const PROFILE_PAGE = 'profile'
export const ERROR_404_PAGE = '404'
export const ERROR_500_PAGE = '500'
export const CHATS_PAGE = 'chats'
